#!/bin/bash

# https://github.com/FelixKratz/JankyBorders/wiki/Man-Page#options

options=(
    style=round
    width=6.0
    hidpi=on
    active_color=0xc089b4fa
    inactive_color=0x00414550
)

borders "${options[@]}"
